### ISSUE TITLE
Shears not working on stacked mob

### ISSUE THREAD

**Issue by LuluxClient** [Rosewood-Development/RoseStacker#40] opened 2021-12-12 10:10 UTC
If you have stacked sheep and you try to shears them it won't work: https://gyazo.com/429e4b221213b6df714cfef753ca25ff

**Comment by LuluxClient** [comment] 2021-12-12 10:12
Also I tried every combination in the config

**Comment by Esophose** [comment] 2021-12-12 11:06
Could you send some additional info such as your server version, config.yml, and entity_settings.yml? Do you have any errors in your console?

**Comment by LuluxClient** [comment] 2021-12-12 12:06
0 errors 
- Config.yml : https://pastebin.com/dWAeEJSi
- Entity.yml : https://pastebin.com/pXT1t3XT


Also I noticed the plugin was taking some server performances, could you check If I need to change something in my configs ?

**Comment by Esophose** [comment] 2021-12-12 12:12
I don't really see any plugin or spawner lag there, it says RoseStacker is using 1.03% if you change the view to plugins there. You can try disabling the legacy-data-migration setting for a performance boost but if you used the /rs convert command from stackmob then don't do that or the conversion will stop. I'll have to look at the shearing thing with your configs a bit later, I'm heading to sleep now.

**Comment by LuluxClient** [comment] 2021-12-12 12:51
> I don't really see any plugin or spawner lag there, it says RoseStacker is using 1.03% if you change the view to plugins there. You can try disabling the legacy-data-migration setting for a performance boost but if you used the /rs convert command from stackmob then don't do that or the conversion will stop. I'll have to look at the shearing thing with your configs a bit later, I'm heading to sleep now.

It's already off and here a new timing: https://spark.lucko.me/YtNRksdUHt

**Comment by LuluxClient** [comment] 2021-12-14 12:33
Any updates on the shear bug ?

**Comment by Esophose** [comment] 2021-12-29 11:30
Sorry about the delay on this, issue was caused by a weird conflict with the cumulative breeding setting being disabled. Fixed in the latest commit. Here's a jar with the fix applied.
[RoseStacker-1.4.1.zip](https://github.com/Rosewood-Development/RoseStacker/files/7788600/RoseStacker-1.4.1.zip)

**Closed by Esophose** 2021-12-29 11:30 UTC
